name: docs test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'dev'

jobs:
  build:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: packages/nestjs-trpc-docs

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install npm modules
        run: pnpm

      - name: Run tests
        run: pnpm test-check

      - name: Build docs
        run: pnpm build
