name: Main PR Check

on:
  pull_request:
    branches:
      - main
      - dev
      - rc
    paths:
      - 'packages/nestjs-trpc/**'

concurrency:
  group: pr-check-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build-check:
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
      HUSKY_SKIP_INSTALL: 1
      CI: true
    defaults:
      run:
        working-directory: packages/nestjs-trpc
    outputs:
      success: ${{ steps.build.outcome == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
      - name: Install pnpm
        run: npm install -g pnpm@latest
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint
        continue-on-error: false
      - name: Build
        id: build
        run: pnpm build
        continue-on-error: false

  comment:
    runs-on: ubuntu-latest
    needs: build-check
    if: always()
    permissions:
      contents: read
      pull-requests: write
      checks: write
    steps:
      - name: Comment PR on success
        if: needs.build-check.result == 'success'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ Build check passed!'
            })
      - name: Comment PR on failure
        if: needs.build-check.result == 'failure'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ Build check failed. Please check the workflow logs for details.'
            }) 