name: Main PR Check

on:
  pull_request_target:
    branches:
      - main
      - dev
      - rc
    paths:
      - 'packages/nestjs-trpc/**'

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  build-check:
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
      HUSKY_SKIP_INSTALL: 1
      CI: true
    defaults:
      run:
        working-directory: packages/nestjs-trpc
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
      - name: Install pnpm
        run: npm install -g pnpm@latest
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint
        continue-on-error: false
      - name: Build
        run: pnpm build
        continue-on-error: false
      - name: Comment PR
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ Build check passed!'
            })
      - name: Comment PR on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ Build check failed. Please check the workflow logs for details.'
            }) 