name: Release

on:
  push:
    branches:
      - main
      - dev
      - rc

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    env:
      HUSKY: 0
      HUSKY_SKIP_INSTALL: 1
      CI: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
      - name: Install pnpm
        run: npm install -g pnpm@latest
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Clean for release
        run: |
          find . -maxdepth 1 -not -name .git -not -name dist -not -name package.json -not -name README.md -not -name CHANGELOG.md -not -name node_modules -not -name . -exec rm -rf {} \;
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        run: npx semantic-release
